services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME:-pockets-web}
    env_file:
      - .env
    networks:
      - default
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-3000}:3000"

networks:
  default:
    driver: bridge